name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17, 21]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        
    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest
        lein: latest
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: clj-deps-${{ hashFiles('deps.edn', 'project.clj') }}
        restore-keys: clj-deps-
        
    - name: Download dependencies
      run: clojure -P -M:test
      
    - name: Run tests
      run: clojure -M:test